#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIR
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TransportCompany")]
	public partial class LinqToSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCiezarowki(Ciezarowki instance);
    partial void UpdateCiezarowki(Ciezarowki instance);
    partial void DeleteCiezarowki(Ciezarowki instance);
    partial void InsertCzesci(Czesci instance);
    partial void UpdateCzesci(Czesci instance);
    partial void DeleteCzesci(Czesci instance);
    partial void InsertFirmy_serwisujace(Firmy_serwisujace instance);
    partial void UpdateFirmy_serwisujace(Firmy_serwisujace instance);
    partial void DeleteFirmy_serwisujace(Firmy_serwisujace instance);
    partial void InsertKlienci(Klienci instance);
    partial void UpdateKlienci(Klienci instance);
    partial void DeleteKlienci(Klienci instance);
    partial void InsertLadunki(Ladunki instance);
    partial void UpdateLadunki(Ladunki instance);
    partial void DeleteLadunki(Ladunki instance);
    partial void InsertPoziomy_zarobkow(Poziomy_zarobkow instance);
    partial void UpdatePoziomy_zarobkow(Poziomy_zarobkow instance);
    partial void DeletePoziomy_zarobkow(Poziomy_zarobkow instance);
    partial void InsertPracownicy(Pracownicy instance);
    partial void UpdatePracownicy(Pracownicy instance);
    partial void DeletePracownicy(Pracownicy instance);
    partial void InsertPrzeglady(Przeglady instance);
    partial void UpdatePrzeglady(Przeglady instance);
    partial void DeletePrzeglady(Przeglady instance);
    partial void InsertRejestr_napraw(Rejestr_napraw instance);
    partial void UpdateRejestr_napraw(Rejestr_napraw instance);
    partial void DeleteRejestr_napraw(Rejestr_napraw instance);
    partial void InsertWymienione_czesci(Wymienione_czesci instance);
    partial void UpdateWymienione_czesci(Wymienione_czesci instance);
    partial void DeleteWymienione_czesci(Wymienione_czesci instance);
    #endregion
		
		public LinqToSQLDataContext() : 
				base(global::TIR.Properties.Settings.Default.TransportCompanyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ciezarowki> Ciezarowkis
		{
			get
			{
				return this.GetTable<Ciezarowki>();
			}
		}
		
		public System.Data.Linq.Table<Czesci> Czescis
		{
			get
			{
				return this.GetTable<Czesci>();
			}
		}
		
		public System.Data.Linq.Table<Firmy_serwisujace> Firmy_serwisujaces
		{
			get
			{
				return this.GetTable<Firmy_serwisujace>();
			}
		}
		
		public System.Data.Linq.Table<Klienci> Kliencis
		{
			get
			{
				return this.GetTable<Klienci>();
			}
		}
		
		public System.Data.Linq.Table<Ladunki> Ladunkis
		{
			get
			{
				return this.GetTable<Ladunki>();
			}
		}
		
		public System.Data.Linq.Table<Poziomy_zarobkow> Poziomy_zarobkows
		{
			get
			{
				return this.GetTable<Poziomy_zarobkow>();
			}
		}
		
		public System.Data.Linq.Table<Pracownicy> Pracownicies
		{
			get
			{
				return this.GetTable<Pracownicy>();
			}
		}
		
		public System.Data.Linq.Table<Przeglady> Przegladies
		{
			get
			{
				return this.GetTable<Przeglady>();
			}
		}
		
		public System.Data.Linq.Table<Rejestr_napraw> Rejestr_napraws
		{
			get
			{
				return this.GetTable<Rejestr_napraw>();
			}
		}
		
		public System.Data.Linq.Table<Wymienione_czesci> Wymienione_czescis
		{
			get
			{
				return this.GetTable<Wymienione_czesci>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ciezarowki")]
	public partial class Ciezarowki : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nr_rejestracyjny_ciezarowki;
		
		private int _rocznik;
		
		private int _maksymalne_dopuszczalne_obciazenie;
		
		private string _kolor;
		
		private string _model;
		
		private string _producent;
		
		private string _nr_pesel_kierowcy;
		
		private EntitySet<Ladunki> _Ladunkis;
		
		private EntitySet<Przeglady> _Przegladies;
		
		private EntitySet<Rejestr_napraw> _Rejestr_napraws;
		
		private EntityRef<Pracownicy> _Pracownicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnr_rejestracyjny_ciezarowkiChanging(string value);
    partial void Onnr_rejestracyjny_ciezarowkiChanged();
    partial void OnrocznikChanging(int value);
    partial void OnrocznikChanged();
    partial void Onmaksymalne_dopuszczalne_obciazenieChanging(int value);
    partial void Onmaksymalne_dopuszczalne_obciazenieChanged();
    partial void OnkolorChanging(string value);
    partial void OnkolorChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnproducentChanging(string value);
    partial void OnproducentChanged();
    partial void Onnr_pesel_kierowcyChanging(string value);
    partial void Onnr_pesel_kierowcyChanged();
    #endregion
		
		public Ciezarowki()
		{
			this._Ladunkis = new EntitySet<Ladunki>(new Action<Ladunki>(this.attach_Ladunkis), new Action<Ladunki>(this.detach_Ladunkis));
			this._Przegladies = new EntitySet<Przeglady>(new Action<Przeglady>(this.attach_Przegladies), new Action<Przeglady>(this.detach_Przegladies));
			this._Rejestr_napraws = new EntitySet<Rejestr_napraw>(new Action<Rejestr_napraw>(this.attach_Rejestr_napraws), new Action<Rejestr_napraw>(this.detach_Rejestr_napraws));
			this._Pracownicy = default(EntityRef<Pracownicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_rejestracyjny_ciezarowki", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nr_rejestracyjny_ciezarowki
		{
			get
			{
				return this._nr_rejestracyjny_ciezarowki;
			}
			set
			{
				if ((this._nr_rejestracyjny_ciezarowki != value))
				{
					this.Onnr_rejestracyjny_ciezarowkiChanging(value);
					this.SendPropertyChanging();
					this._nr_rejestracyjny_ciezarowki = value;
					this.SendPropertyChanged("nr_rejestracyjny_ciezarowki");
					this.Onnr_rejestracyjny_ciezarowkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rocznik", DbType="Int NOT NULL")]
		public int rocznik
		{
			get
			{
				return this._rocznik;
			}
			set
			{
				if ((this._rocznik != value))
				{
					this.OnrocznikChanging(value);
					this.SendPropertyChanging();
					this._rocznik = value;
					this.SendPropertyChanged("rocznik");
					this.OnrocznikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maksymalne_dopuszczalne_obciazenie", DbType="Int NOT NULL")]
		public int maksymalne_dopuszczalne_obciazenie
		{
			get
			{
				return this._maksymalne_dopuszczalne_obciazenie;
			}
			set
			{
				if ((this._maksymalne_dopuszczalne_obciazenie != value))
				{
					this.Onmaksymalne_dopuszczalne_obciazenieChanging(value);
					this.SendPropertyChanging();
					this._maksymalne_dopuszczalne_obciazenie = value;
					this.SendPropertyChanged("maksymalne_dopuszczalne_obciazenie");
					this.Onmaksymalne_dopuszczalne_obciazenieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kolor", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string kolor
		{
			get
			{
				return this._kolor;
			}
			set
			{
				if ((this._kolor != value))
				{
					this.OnkolorChanging(value);
					this.SendPropertyChanging();
					this._kolor = value;
					this.SendPropertyChanged("kolor");
					this.OnkolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producent", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string producent
		{
			get
			{
				return this._producent;
			}
			set
			{
				if ((this._producent != value))
				{
					this.OnproducentChanging(value);
					this.SendPropertyChanging();
					this._producent = value;
					this.SendPropertyChanged("producent");
					this.OnproducentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_pesel_kierowcy", DbType="VarChar(11)")]
		public string nr_pesel_kierowcy
		{
			get
			{
				return this._nr_pesel_kierowcy;
			}
			set
			{
				if ((this._nr_pesel_kierowcy != value))
				{
					if (this._Pracownicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnr_pesel_kierowcyChanging(value);
					this.SendPropertyChanging();
					this._nr_pesel_kierowcy = value;
					this.SendPropertyChanged("nr_pesel_kierowcy");
					this.Onnr_pesel_kierowcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciezarowki_Ladunki", Storage="_Ladunkis", ThisKey="nr_rejestracyjny_ciezarowki", OtherKey="nr_rejestracyjny_ciezarowki")]
		public EntitySet<Ladunki> Ladunkis
		{
			get
			{
				return this._Ladunkis;
			}
			set
			{
				this._Ladunkis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciezarowki_Przeglady", Storage="_Przegladies", ThisKey="nr_rejestracyjny_ciezarowki", OtherKey="nr_rejestracyjny_ciezarowki")]
		public EntitySet<Przeglady> Przegladies
		{
			get
			{
				return this._Przegladies;
			}
			set
			{
				this._Przegladies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciezarowki_Rejestr_napraw", Storage="_Rejestr_napraws", ThisKey="nr_rejestracyjny_ciezarowki", OtherKey="nr_rejestracyjny_ciezarowki")]
		public EntitySet<Rejestr_napraw> Rejestr_napraws
		{
			get
			{
				return this._Rejestr_napraws;
			}
			set
			{
				this._Rejestr_napraws.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pracownicy_Ciezarowki", Storage="_Pracownicy", ThisKey="nr_pesel_kierowcy", OtherKey="nr_pesel", IsForeignKey=true)]
		public Pracownicy Pracownicy
		{
			get
			{
				return this._Pracownicy.Entity;
			}
			set
			{
				Pracownicy previousValue = this._Pracownicy.Entity;
				if (((previousValue != value) 
							|| (this._Pracownicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pracownicy.Entity = null;
						previousValue.Ciezarowkis.Remove(this);
					}
					this._Pracownicy.Entity = value;
					if ((value != null))
					{
						value.Ciezarowkis.Add(this);
						this._nr_pesel_kierowcy = value.nr_pesel;
					}
					else
					{
						this._nr_pesel_kierowcy = default(string);
					}
					this.SendPropertyChanged("Pracownicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ladunkis(Ladunki entity)
		{
			this.SendPropertyChanging();
			entity.Ciezarowki = this;
		}
		
		private void detach_Ladunkis(Ladunki entity)
		{
			this.SendPropertyChanging();
			entity.Ciezarowki = null;
		}
		
		private void attach_Przegladies(Przeglady entity)
		{
			this.SendPropertyChanging();
			entity.Ciezarowki = this;
		}
		
		private void detach_Przegladies(Przeglady entity)
		{
			this.SendPropertyChanging();
			entity.Ciezarowki = null;
		}
		
		private void attach_Rejestr_napraws(Rejestr_napraw entity)
		{
			this.SendPropertyChanging();
			entity.Ciezarowki = this;
		}
		
		private void detach_Rejestr_napraws(Rejestr_napraw entity)
		{
			this.SendPropertyChanging();
			entity.Ciezarowki = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Czesci")]
	public partial class Czesci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_czesci;
		
		private string _nazwa_czesci;
		
		private decimal _koszt_czesci;
		
		private EntitySet<Wymienione_czesci> _Wymienione_czescis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_czesciChanging(int value);
    partial void Onid_czesciChanged();
    partial void Onnazwa_czesciChanging(string value);
    partial void Onnazwa_czesciChanged();
    partial void Onkoszt_czesciChanging(decimal value);
    partial void Onkoszt_czesciChanged();
    #endregion
		
		public Czesci()
		{
			this._Wymienione_czescis = new EntitySet<Wymienione_czesci>(new Action<Wymienione_czesci>(this.attach_Wymienione_czescis), new Action<Wymienione_czesci>(this.detach_Wymienione_czescis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czesci", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_czesci
		{
			get
			{
				return this._id_czesci;
			}
			set
			{
				if ((this._id_czesci != value))
				{
					this.Onid_czesciChanging(value);
					this.SendPropertyChanging();
					this._id_czesci = value;
					this.SendPropertyChanged("id_czesci");
					this.Onid_czesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_czesci", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nazwa_czesci
		{
			get
			{
				return this._nazwa_czesci;
			}
			set
			{
				if ((this._nazwa_czesci != value))
				{
					this.Onnazwa_czesciChanging(value);
					this.SendPropertyChanging();
					this._nazwa_czesci = value;
					this.SendPropertyChanged("nazwa_czesci");
					this.Onnazwa_czesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_koszt_czesci", DbType="Decimal(12,2) NOT NULL")]
		public decimal koszt_czesci
		{
			get
			{
				return this._koszt_czesci;
			}
			set
			{
				if ((this._koszt_czesci != value))
				{
					this.Onkoszt_czesciChanging(value);
					this.SendPropertyChanging();
					this._koszt_czesci = value;
					this.SendPropertyChanged("koszt_czesci");
					this.Onkoszt_czesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czesci_Wymienione_czesci", Storage="_Wymienione_czescis", ThisKey="id_czesci", OtherKey="id_czesci")]
		public EntitySet<Wymienione_czesci> Wymienione_czescis
		{
			get
			{
				return this._Wymienione_czescis;
			}
			set
			{
				this._Wymienione_czescis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wymienione_czescis(Wymienione_czesci entity)
		{
			this.SendPropertyChanging();
			entity.Czesci = this;
		}
		
		private void detach_Wymienione_czescis(Wymienione_czesci entity)
		{
			this.SendPropertyChanging();
			entity.Czesci = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Firmy_serwisujace")]
	public partial class Firmy_serwisujace : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nr_nip;
		
		private string _nazwa;
		
		private string _adres;
		
		private string _nr_telefonu;
		
		private EntitySet<Przeglady> _Przegladies;
		
		private EntitySet<Rejestr_napraw> _Rejestr_napraws;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnr_nipChanging(int value);
    partial void Onnr_nipChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void Onnr_telefonuChanging(string value);
    partial void Onnr_telefonuChanged();
    #endregion
		
		public Firmy_serwisujace()
		{
			this._Przegladies = new EntitySet<Przeglady>(new Action<Przeglady>(this.attach_Przegladies), new Action<Przeglady>(this.detach_Przegladies));
			this._Rejestr_napraws = new EntitySet<Rejestr_napraw>(new Action<Rejestr_napraw>(this.attach_Rejestr_napraws), new Action<Rejestr_napraw>(this.detach_Rejestr_napraws));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_nip", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nr_nip
		{
			get
			{
				return this._nr_nip;
			}
			set
			{
				if ((this._nr_nip != value))
				{
					this.Onnr_nipChanging(value);
					this.SendPropertyChanging();
					this._nr_nip = value;
					this.SendPropertyChanged("nr_nip");
					this.Onnr_nipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_telefonu", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string nr_telefonu
		{
			get
			{
				return this._nr_telefonu;
			}
			set
			{
				if ((this._nr_telefonu != value))
				{
					this.Onnr_telefonuChanging(value);
					this.SendPropertyChanging();
					this._nr_telefonu = value;
					this.SendPropertyChanged("nr_telefonu");
					this.Onnr_telefonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firmy_serwisujace_Przeglady", Storage="_Przegladies", ThisKey="nr_nip", OtherKey="nr_nip_serwisu")]
		public EntitySet<Przeglady> Przegladies
		{
			get
			{
				return this._Przegladies;
			}
			set
			{
				this._Przegladies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firmy_serwisujace_Rejestr_napraw", Storage="_Rejestr_napraws", ThisKey="nr_nip", OtherKey="nr_nip_serwisu")]
		public EntitySet<Rejestr_napraw> Rejestr_napraws
		{
			get
			{
				return this._Rejestr_napraws;
			}
			set
			{
				this._Rejestr_napraws.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Przegladies(Przeglady entity)
		{
			this.SendPropertyChanging();
			entity.Firmy_serwisujace = this;
		}
		
		private void detach_Przegladies(Przeglady entity)
		{
			this.SendPropertyChanging();
			entity.Firmy_serwisujace = null;
		}
		
		private void attach_Rejestr_napraws(Rejestr_napraw entity)
		{
			this.SendPropertyChanging();
			entity.Firmy_serwisujace = this;
		}
		
		private void detach_Rejestr_napraws(Rejestr_napraw entity)
		{
			this.SendPropertyChanging();
			entity.Firmy_serwisujace = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klienci")]
	public partial class Klienci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_klienta;
		
		private string _imie;
		
		private string _nazwisko;
		
		private string _adres_zamieszkania;
		
		private string _nr_telefonu;
		
		private EntitySet<Ladunki> _Ladunkis;
		
		private EntitySet<Ladunki> _Ladunkis1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klientaChanging(int value);
    partial void Onid_klientaChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void Onadres_zamieszkaniaChanging(string value);
    partial void Onadres_zamieszkaniaChanged();
    partial void Onnr_telefonuChanging(string value);
    partial void Onnr_telefonuChanged();
    #endregion
		
		public Klienci()
		{
			this._Ladunkis = new EntitySet<Ladunki>(new Action<Ladunki>(this.attach_Ladunkis), new Action<Ladunki>(this.detach_Ladunkis));
			this._Ladunkis1 = new EntitySet<Ladunki>(new Action<Ladunki>(this.attach_Ladunkis1), new Action<Ladunki>(this.detach_Ladunkis1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this.Onid_klientaChanging(value);
					this.SendPropertyChanging();
					this._id_klienta = value;
					this.SendPropertyChanged("id_klienta");
					this.Onid_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_zamieszkania", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adres_zamieszkania
		{
			get
			{
				return this._adres_zamieszkania;
			}
			set
			{
				if ((this._adres_zamieszkania != value))
				{
					this.Onadres_zamieszkaniaChanging(value);
					this.SendPropertyChanging();
					this._adres_zamieszkania = value;
					this.SendPropertyChanged("adres_zamieszkania");
					this.Onadres_zamieszkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_telefonu", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string nr_telefonu
		{
			get
			{
				return this._nr_telefonu;
			}
			set
			{
				if ((this._nr_telefonu != value))
				{
					this.Onnr_telefonuChanging(value);
					this.SendPropertyChanging();
					this._nr_telefonu = value;
					this.SendPropertyChanged("nr_telefonu");
					this.Onnr_telefonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Ladunki", Storage="_Ladunkis", ThisKey="id_klienta", OtherKey="id_nadawcy")]
		public EntitySet<Ladunki> Ladunkis
		{
			get
			{
				return this._Ladunkis;
			}
			set
			{
				this._Ladunkis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Ladunki1", Storage="_Ladunkis1", ThisKey="id_klienta", OtherKey="id_odbiorcy")]
		public EntitySet<Ladunki> Ladunkis1
		{
			get
			{
				return this._Ladunkis1;
			}
			set
			{
				this._Ladunkis1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ladunkis(Ladunki entity)
		{
			this.SendPropertyChanging();
			entity.Klienci = this;
		}
		
		private void detach_Ladunkis(Ladunki entity)
		{
			this.SendPropertyChanging();
			entity.Klienci = null;
		}
		
		private void attach_Ladunkis1(Ladunki entity)
		{
			this.SendPropertyChanging();
			entity.Klienci1 = this;
		}
		
		private void detach_Ladunkis1(Ladunki entity)
		{
			this.SendPropertyChanging();
			entity.Klienci1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ladunki")]
	public partial class Ladunki : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ladunku;
		
		private int _waga;
		
		private string _nazwa_ladunku;
		
		private string _rodzaj_ladunku;
		
		private string _adres_startowy;
		
		private string _adres_docelowy;
		
		private System.DateTime _data_nadania;
		
		private System.Nullable<System.DateTime> _data_odbioru;
		
		private string _nr_rejestracyjny_ciezarowki;
		
		private int _id_nadawcy;
		
		private int _id_odbiorcy;
		
		private EntityRef<Klienci> _Klienci;
		
		private EntityRef<Klienci> _Klienci1;
		
		private EntityRef<Ciezarowki> _Ciezarowki;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ladunkuChanging(int value);
    partial void Onid_ladunkuChanged();
    partial void OnwagaChanging(int value);
    partial void OnwagaChanged();
    partial void Onnazwa_ladunkuChanging(string value);
    partial void Onnazwa_ladunkuChanged();
    partial void Onrodzaj_ladunkuChanging(string value);
    partial void Onrodzaj_ladunkuChanged();
    partial void Onadres_startowyChanging(string value);
    partial void Onadres_startowyChanged();
    partial void Onadres_docelowyChanging(string value);
    partial void Onadres_docelowyChanged();
    partial void Ondata_nadaniaChanging(System.DateTime value);
    partial void Ondata_nadaniaChanged();
    partial void Ondata_odbioruChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_odbioruChanged();
    partial void Onnr_rejestracyjny_ciezarowkiChanging(string value);
    partial void Onnr_rejestracyjny_ciezarowkiChanged();
    partial void Onid_nadawcyChanging(int value);
    partial void Onid_nadawcyChanged();
    partial void Onid_odbiorcyChanging(int value);
    partial void Onid_odbiorcyChanged();
    #endregion
		
		public Ladunki()
		{
			this._Klienci = default(EntityRef<Klienci>);
			this._Klienci1 = default(EntityRef<Klienci>);
			this._Ciezarowki = default(EntityRef<Ciezarowki>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ladunku", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ladunku
		{
			get
			{
				return this._id_ladunku;
			}
			set
			{
				if ((this._id_ladunku != value))
				{
					this.Onid_ladunkuChanging(value);
					this.SendPropertyChanging();
					this._id_ladunku = value;
					this.SendPropertyChanged("id_ladunku");
					this.Onid_ladunkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waga", DbType="Int NOT NULL")]
		public int waga
		{
			get
			{
				return this._waga;
			}
			set
			{
				if ((this._waga != value))
				{
					this.OnwagaChanging(value);
					this.SendPropertyChanging();
					this._waga = value;
					this.SendPropertyChanged("waga");
					this.OnwagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_ladunku", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nazwa_ladunku
		{
			get
			{
				return this._nazwa_ladunku;
			}
			set
			{
				if ((this._nazwa_ladunku != value))
				{
					this.Onnazwa_ladunkuChanging(value);
					this.SendPropertyChanging();
					this._nazwa_ladunku = value;
					this.SendPropertyChanged("nazwa_ladunku");
					this.Onnazwa_ladunkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rodzaj_ladunku", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string rodzaj_ladunku
		{
			get
			{
				return this._rodzaj_ladunku;
			}
			set
			{
				if ((this._rodzaj_ladunku != value))
				{
					this.Onrodzaj_ladunkuChanging(value);
					this.SendPropertyChanging();
					this._rodzaj_ladunku = value;
					this.SendPropertyChanged("rodzaj_ladunku");
					this.Onrodzaj_ladunkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_startowy", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adres_startowy
		{
			get
			{
				return this._adres_startowy;
			}
			set
			{
				if ((this._adres_startowy != value))
				{
					this.Onadres_startowyChanging(value);
					this.SendPropertyChanging();
					this._adres_startowy = value;
					this.SendPropertyChanged("adres_startowy");
					this.Onadres_startowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_docelowy", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adres_docelowy
		{
			get
			{
				return this._adres_docelowy;
			}
			set
			{
				if ((this._adres_docelowy != value))
				{
					this.Onadres_docelowyChanging(value);
					this.SendPropertyChanging();
					this._adres_docelowy = value;
					this.SendPropertyChanged("adres_docelowy");
					this.Onadres_docelowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nadania", DbType="SmallDateTime NOT NULL")]
		public System.DateTime data_nadania
		{
			get
			{
				return this._data_nadania;
			}
			set
			{
				if ((this._data_nadania != value))
				{
					this.Ondata_nadaniaChanging(value);
					this.SendPropertyChanging();
					this._data_nadania = value;
					this.SendPropertyChanged("data_nadania");
					this.Ondata_nadaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_odbioru", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> data_odbioru
		{
			get
			{
				return this._data_odbioru;
			}
			set
			{
				if ((this._data_odbioru != value))
				{
					this.Ondata_odbioruChanging(value);
					this.SendPropertyChanging();
					this._data_odbioru = value;
					this.SendPropertyChanged("data_odbioru");
					this.Ondata_odbioruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_rejestracyjny_ciezarowki", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nr_rejestracyjny_ciezarowki
		{
			get
			{
				return this._nr_rejestracyjny_ciezarowki;
			}
			set
			{
				if ((this._nr_rejestracyjny_ciezarowki != value))
				{
					if (this._Ciezarowki.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnr_rejestracyjny_ciezarowkiChanging(value);
					this.SendPropertyChanging();
					this._nr_rejestracyjny_ciezarowki = value;
					this.SendPropertyChanged("nr_rejestracyjny_ciezarowki");
					this.Onnr_rejestracyjny_ciezarowkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nadawcy", DbType="Int NOT NULL")]
		public int id_nadawcy
		{
			get
			{
				return this._id_nadawcy;
			}
			set
			{
				if ((this._id_nadawcy != value))
				{
					if (this._Klienci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nadawcyChanging(value);
					this.SendPropertyChanging();
					this._id_nadawcy = value;
					this.SendPropertyChanged("id_nadawcy");
					this.Onid_nadawcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_odbiorcy", DbType="Int NOT NULL")]
		public int id_odbiorcy
		{
			get
			{
				return this._id_odbiorcy;
			}
			set
			{
				if ((this._id_odbiorcy != value))
				{
					if (this._Klienci1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_odbiorcyChanging(value);
					this.SendPropertyChanging();
					this._id_odbiorcy = value;
					this.SendPropertyChanged("id_odbiorcy");
					this.Onid_odbiorcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Ladunki", Storage="_Klienci", ThisKey="id_nadawcy", OtherKey="id_klienta", IsForeignKey=true)]
		public Klienci Klienci
		{
			get
			{
				return this._Klienci.Entity;
			}
			set
			{
				Klienci previousValue = this._Klienci.Entity;
				if (((previousValue != value) 
							|| (this._Klienci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klienci.Entity = null;
						previousValue.Ladunkis.Remove(this);
					}
					this._Klienci.Entity = value;
					if ((value != null))
					{
						value.Ladunkis.Add(this);
						this._id_nadawcy = value.id_klienta;
					}
					else
					{
						this._id_nadawcy = default(int);
					}
					this.SendPropertyChanged("Klienci");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Ladunki1", Storage="_Klienci1", ThisKey="id_odbiorcy", OtherKey="id_klienta", IsForeignKey=true)]
		public Klienci Klienci1
		{
			get
			{
				return this._Klienci1.Entity;
			}
			set
			{
				Klienci previousValue = this._Klienci1.Entity;
				if (((previousValue != value) 
							|| (this._Klienci1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klienci1.Entity = null;
						previousValue.Ladunkis1.Remove(this);
					}
					this._Klienci1.Entity = value;
					if ((value != null))
					{
						value.Ladunkis1.Add(this);
						this._id_odbiorcy = value.id_klienta;
					}
					else
					{
						this._id_odbiorcy = default(int);
					}
					this.SendPropertyChanged("Klienci1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciezarowki_Ladunki", Storage="_Ciezarowki", ThisKey="nr_rejestracyjny_ciezarowki", OtherKey="nr_rejestracyjny_ciezarowki", IsForeignKey=true)]
		public Ciezarowki Ciezarowki
		{
			get
			{
				return this._Ciezarowki.Entity;
			}
			set
			{
				Ciezarowki previousValue = this._Ciezarowki.Entity;
				if (((previousValue != value) 
							|| (this._Ciezarowki.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciezarowki.Entity = null;
						previousValue.Ladunkis.Remove(this);
					}
					this._Ciezarowki.Entity = value;
					if ((value != null))
					{
						value.Ladunkis.Add(this);
						this._nr_rejestracyjny_ciezarowki = value.nr_rejestracyjny_ciezarowki;
					}
					else
					{
						this._nr_rejestracyjny_ciezarowki = default(string);
					}
					this.SendPropertyChanged("Ciezarowki");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Poziomy_zarobkow")]
	public partial class Poziomy_zarobkow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nr_przedzialu;
		
		private decimal _dolna_granica;
		
		private decimal _gorna_granica;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnr_przedzialuChanging(int value);
    partial void Onnr_przedzialuChanged();
    partial void Ondolna_granicaChanging(decimal value);
    partial void Ondolna_granicaChanged();
    partial void Ongorna_granicaChanging(decimal value);
    partial void Ongorna_granicaChanged();
    #endregion
		
		public Poziomy_zarobkow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_przedzialu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nr_przedzialu
		{
			get
			{
				return this._nr_przedzialu;
			}
			set
			{
				if ((this._nr_przedzialu != value))
				{
					this.Onnr_przedzialuChanging(value);
					this.SendPropertyChanging();
					this._nr_przedzialu = value;
					this.SendPropertyChanged("nr_przedzialu");
					this.Onnr_przedzialuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dolna_granica", DbType="Decimal(12,2) NOT NULL")]
		public decimal dolna_granica
		{
			get
			{
				return this._dolna_granica;
			}
			set
			{
				if ((this._dolna_granica != value))
				{
					this.Ondolna_granicaChanging(value);
					this.SendPropertyChanging();
					this._dolna_granica = value;
					this.SendPropertyChanged("dolna_granica");
					this.Ondolna_granicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gorna_granica", DbType="Decimal(12,2) NOT NULL")]
		public decimal gorna_granica
		{
			get
			{
				return this._gorna_granica;
			}
			set
			{
				if ((this._gorna_granica != value))
				{
					this.Ongorna_granicaChanging(value);
					this.SendPropertyChanging();
					this._gorna_granica = value;
					this.SendPropertyChanged("gorna_granica");
					this.Ongorna_granicaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pracownicy")]
	public partial class Pracownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nr_pesel;
		
		private string _imie;
		
		private string _nazwisko;
		
		private decimal _pensja;
		
		private string _stanowisko;
		
		private string _adres_zamieszkania;
		
		private string _adres_zatrudnienia;
		
		private EntitySet<Ciezarowki> _Ciezarowkis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnr_peselChanging(string value);
    partial void Onnr_peselChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void OnpensjaChanging(decimal value);
    partial void OnpensjaChanged();
    partial void OnstanowiskoChanging(string value);
    partial void OnstanowiskoChanged();
    partial void Onadres_zamieszkaniaChanging(string value);
    partial void Onadres_zamieszkaniaChanged();
    partial void Onadres_zatrudnieniaChanging(string value);
    partial void Onadres_zatrudnieniaChanged();
    #endregion
		
		public Pracownicy()
		{
			this._Ciezarowkis = new EntitySet<Ciezarowki>(new Action<Ciezarowki>(this.attach_Ciezarowkis), new Action<Ciezarowki>(this.detach_Ciezarowkis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_pesel", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nr_pesel
		{
			get
			{
				return this._nr_pesel;
			}
			set
			{
				if ((this._nr_pesel != value))
				{
					this.Onnr_peselChanging(value);
					this.SendPropertyChanging();
					this._nr_pesel = value;
					this.SendPropertyChanged("nr_pesel");
					this.Onnr_peselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pensja", DbType="Decimal(12,2) NOT NULL")]
		public decimal pensja
		{
			get
			{
				return this._pensja;
			}
			set
			{
				if ((this._pensja != value))
				{
					this.OnpensjaChanging(value);
					this.SendPropertyChanging();
					this._pensja = value;
					this.SendPropertyChanged("pensja");
					this.OnpensjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stanowisko", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stanowisko
		{
			get
			{
				return this._stanowisko;
			}
			set
			{
				if ((this._stanowisko != value))
				{
					this.OnstanowiskoChanging(value);
					this.SendPropertyChanging();
					this._stanowisko = value;
					this.SendPropertyChanged("stanowisko");
					this.OnstanowiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_zamieszkania", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adres_zamieszkania
		{
			get
			{
				return this._adres_zamieszkania;
			}
			set
			{
				if ((this._adres_zamieszkania != value))
				{
					this.Onadres_zamieszkaniaChanging(value);
					this.SendPropertyChanging();
					this._adres_zamieszkania = value;
					this.SendPropertyChanged("adres_zamieszkania");
					this.Onadres_zamieszkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_zatrudnienia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adres_zatrudnienia
		{
			get
			{
				return this._adres_zatrudnienia;
			}
			set
			{
				if ((this._adres_zatrudnienia != value))
				{
					this.Onadres_zatrudnieniaChanging(value);
					this.SendPropertyChanging();
					this._adres_zatrudnienia = value;
					this.SendPropertyChanged("adres_zatrudnienia");
					this.Onadres_zatrudnieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pracownicy_Ciezarowki", Storage="_Ciezarowkis", ThisKey="nr_pesel", OtherKey="nr_pesel_kierowcy")]
		public EntitySet<Ciezarowki> Ciezarowkis
		{
			get
			{
				return this._Ciezarowkis;
			}
			set
			{
				this._Ciezarowkis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ciezarowkis(Ciezarowki entity)
		{
			this.SendPropertyChanging();
			entity.Pracownicy = this;
		}
		
		private void detach_Ciezarowkis(Ciezarowki entity)
		{
			this.SendPropertyChanging();
			entity.Pracownicy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Przeglady")]
	public partial class Przeglady : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nr_rejestracyjny_ciezarowki;
		
		private System.DateTime _data_przegladu;
		
		private int _nr_nip_serwisu;
		
		private System.DateTime _data_nastepnego_serwisu;
		
		private EntityRef<Firmy_serwisujace> _Firmy_serwisujace;
		
		private EntityRef<Ciezarowki> _Ciezarowki;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnr_rejestracyjny_ciezarowkiChanging(string value);
    partial void Onnr_rejestracyjny_ciezarowkiChanged();
    partial void Ondata_przegladuChanging(System.DateTime value);
    partial void Ondata_przegladuChanged();
    partial void Onnr_nip_serwisuChanging(int value);
    partial void Onnr_nip_serwisuChanged();
    partial void Ondata_nastepnego_serwisuChanging(System.DateTime value);
    partial void Ondata_nastepnego_serwisuChanged();
    #endregion
		
		public Przeglady()
		{
			this._Firmy_serwisujace = default(EntityRef<Firmy_serwisujace>);
			this._Ciezarowki = default(EntityRef<Ciezarowki>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_rejestracyjny_ciezarowki", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nr_rejestracyjny_ciezarowki
		{
			get
			{
				return this._nr_rejestracyjny_ciezarowki;
			}
			set
			{
				if ((this._nr_rejestracyjny_ciezarowki != value))
				{
					if (this._Ciezarowki.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnr_rejestracyjny_ciezarowkiChanging(value);
					this.SendPropertyChanging();
					this._nr_rejestracyjny_ciezarowki = value;
					this.SendPropertyChanged("nr_rejestracyjny_ciezarowki");
					this.Onnr_rejestracyjny_ciezarowkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_przegladu", DbType="SmallDateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime data_przegladu
		{
			get
			{
				return this._data_przegladu;
			}
			set
			{
				if ((this._data_przegladu != value))
				{
					this.Ondata_przegladuChanging(value);
					this.SendPropertyChanging();
					this._data_przegladu = value;
					this.SendPropertyChanged("data_przegladu");
					this.Ondata_przegladuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_nip_serwisu", DbType="Int NOT NULL")]
		public int nr_nip_serwisu
		{
			get
			{
				return this._nr_nip_serwisu;
			}
			set
			{
				if ((this._nr_nip_serwisu != value))
				{
					if (this._Firmy_serwisujace.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnr_nip_serwisuChanging(value);
					this.SendPropertyChanging();
					this._nr_nip_serwisu = value;
					this.SendPropertyChanged("nr_nip_serwisu");
					this.Onnr_nip_serwisuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nastepnego_serwisu", DbType="SmallDateTime NOT NULL")]
		public System.DateTime data_nastepnego_serwisu
		{
			get
			{
				return this._data_nastepnego_serwisu;
			}
			set
			{
				if ((this._data_nastepnego_serwisu != value))
				{
					this.Ondata_nastepnego_serwisuChanging(value);
					this.SendPropertyChanging();
					this._data_nastepnego_serwisu = value;
					this.SendPropertyChanged("data_nastepnego_serwisu");
					this.Ondata_nastepnego_serwisuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firmy_serwisujace_Przeglady", Storage="_Firmy_serwisujace", ThisKey="nr_nip_serwisu", OtherKey="nr_nip", IsForeignKey=true)]
		public Firmy_serwisujace Firmy_serwisujace
		{
			get
			{
				return this._Firmy_serwisujace.Entity;
			}
			set
			{
				Firmy_serwisujace previousValue = this._Firmy_serwisujace.Entity;
				if (((previousValue != value) 
							|| (this._Firmy_serwisujace.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Firmy_serwisujace.Entity = null;
						previousValue.Przegladies.Remove(this);
					}
					this._Firmy_serwisujace.Entity = value;
					if ((value != null))
					{
						value.Przegladies.Add(this);
						this._nr_nip_serwisu = value.nr_nip;
					}
					else
					{
						this._nr_nip_serwisu = default(int);
					}
					this.SendPropertyChanged("Firmy_serwisujace");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciezarowki_Przeglady", Storage="_Ciezarowki", ThisKey="nr_rejestracyjny_ciezarowki", OtherKey="nr_rejestracyjny_ciezarowki", IsForeignKey=true)]
		public Ciezarowki Ciezarowki
		{
			get
			{
				return this._Ciezarowki.Entity;
			}
			set
			{
				Ciezarowki previousValue = this._Ciezarowki.Entity;
				if (((previousValue != value) 
							|| (this._Ciezarowki.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciezarowki.Entity = null;
						previousValue.Przegladies.Remove(this);
					}
					this._Ciezarowki.Entity = value;
					if ((value != null))
					{
						value.Przegladies.Add(this);
						this._nr_rejestracyjny_ciezarowki = value.nr_rejestracyjny_ciezarowki;
					}
					else
					{
						this._nr_rejestracyjny_ciezarowki = default(string);
					}
					this.SendPropertyChanged("Ciezarowki");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rejestr_napraw")]
	public partial class Rejestr_napraw : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nr_faktury;
		
		private string _nr_rejestracyjny_ciezarowki;
		
		private System.DateTime _data_naprawy;
		
		private int _nr_nip_serwisu;
		
		private decimal _koszt_robocizny;
		
		private EntitySet<Wymienione_czesci> _Wymienione_czescis;
		
		private EntityRef<Firmy_serwisujace> _Firmy_serwisujace;
		
		private EntityRef<Ciezarowki> _Ciezarowki;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnr_fakturyChanging(int value);
    partial void Onnr_fakturyChanged();
    partial void Onnr_rejestracyjny_ciezarowkiChanging(string value);
    partial void Onnr_rejestracyjny_ciezarowkiChanged();
    partial void Ondata_naprawyChanging(System.DateTime value);
    partial void Ondata_naprawyChanged();
    partial void Onnr_nip_serwisuChanging(int value);
    partial void Onnr_nip_serwisuChanged();
    partial void Onkoszt_robociznyChanging(decimal value);
    partial void Onkoszt_robociznyChanged();
    #endregion
		
		public Rejestr_napraw()
		{
			this._Wymienione_czescis = new EntitySet<Wymienione_czesci>(new Action<Wymienione_czesci>(this.attach_Wymienione_czescis), new Action<Wymienione_czesci>(this.detach_Wymienione_czescis));
			this._Firmy_serwisujace = default(EntityRef<Firmy_serwisujace>);
			this._Ciezarowki = default(EntityRef<Ciezarowki>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_faktury", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nr_faktury
		{
			get
			{
				return this._nr_faktury;
			}
			set
			{
				if ((this._nr_faktury != value))
				{
					this.Onnr_fakturyChanging(value);
					this.SendPropertyChanging();
					this._nr_faktury = value;
					this.SendPropertyChanged("nr_faktury");
					this.Onnr_fakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_rejestracyjny_ciezarowki", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nr_rejestracyjny_ciezarowki
		{
			get
			{
				return this._nr_rejestracyjny_ciezarowki;
			}
			set
			{
				if ((this._nr_rejestracyjny_ciezarowki != value))
				{
					if (this._Ciezarowki.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnr_rejestracyjny_ciezarowkiChanging(value);
					this.SendPropertyChanging();
					this._nr_rejestracyjny_ciezarowki = value;
					this.SendPropertyChanged("nr_rejestracyjny_ciezarowki");
					this.Onnr_rejestracyjny_ciezarowkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_naprawy", DbType="SmallDateTime NOT NULL")]
		public System.DateTime data_naprawy
		{
			get
			{
				return this._data_naprawy;
			}
			set
			{
				if ((this._data_naprawy != value))
				{
					this.Ondata_naprawyChanging(value);
					this.SendPropertyChanging();
					this._data_naprawy = value;
					this.SendPropertyChanged("data_naprawy");
					this.Ondata_naprawyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_nip_serwisu", DbType="Int NOT NULL")]
		public int nr_nip_serwisu
		{
			get
			{
				return this._nr_nip_serwisu;
			}
			set
			{
				if ((this._nr_nip_serwisu != value))
				{
					if (this._Firmy_serwisujace.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnr_nip_serwisuChanging(value);
					this.SendPropertyChanging();
					this._nr_nip_serwisu = value;
					this.SendPropertyChanged("nr_nip_serwisu");
					this.Onnr_nip_serwisuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_koszt_robocizny", DbType="Decimal(12,2) NOT NULL")]
		public decimal koszt_robocizny
		{
			get
			{
				return this._koszt_robocizny;
			}
			set
			{
				if ((this._koszt_robocizny != value))
				{
					this.Onkoszt_robociznyChanging(value);
					this.SendPropertyChanging();
					this._koszt_robocizny = value;
					this.SendPropertyChanged("koszt_robocizny");
					this.Onkoszt_robociznyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rejestr_napraw_Wymienione_czesci", Storage="_Wymienione_czescis", ThisKey="nr_faktury", OtherKey="nr_faktury")]
		public EntitySet<Wymienione_czesci> Wymienione_czescis
		{
			get
			{
				return this._Wymienione_czescis;
			}
			set
			{
				this._Wymienione_czescis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firmy_serwisujace_Rejestr_napraw", Storage="_Firmy_serwisujace", ThisKey="nr_nip_serwisu", OtherKey="nr_nip", IsForeignKey=true)]
		public Firmy_serwisujace Firmy_serwisujace
		{
			get
			{
				return this._Firmy_serwisujace.Entity;
			}
			set
			{
				Firmy_serwisujace previousValue = this._Firmy_serwisujace.Entity;
				if (((previousValue != value) 
							|| (this._Firmy_serwisujace.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Firmy_serwisujace.Entity = null;
						previousValue.Rejestr_napraws.Remove(this);
					}
					this._Firmy_serwisujace.Entity = value;
					if ((value != null))
					{
						value.Rejestr_napraws.Add(this);
						this._nr_nip_serwisu = value.nr_nip;
					}
					else
					{
						this._nr_nip_serwisu = default(int);
					}
					this.SendPropertyChanged("Firmy_serwisujace");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciezarowki_Rejestr_napraw", Storage="_Ciezarowki", ThisKey="nr_rejestracyjny_ciezarowki", OtherKey="nr_rejestracyjny_ciezarowki", IsForeignKey=true)]
		public Ciezarowki Ciezarowki
		{
			get
			{
				return this._Ciezarowki.Entity;
			}
			set
			{
				Ciezarowki previousValue = this._Ciezarowki.Entity;
				if (((previousValue != value) 
							|| (this._Ciezarowki.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciezarowki.Entity = null;
						previousValue.Rejestr_napraws.Remove(this);
					}
					this._Ciezarowki.Entity = value;
					if ((value != null))
					{
						value.Rejestr_napraws.Add(this);
						this._nr_rejestracyjny_ciezarowki = value.nr_rejestracyjny_ciezarowki;
					}
					else
					{
						this._nr_rejestracyjny_ciezarowki = default(string);
					}
					this.SendPropertyChanged("Ciezarowki");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wymienione_czescis(Wymienione_czesci entity)
		{
			this.SendPropertyChanging();
			entity.Rejestr_napraw = this;
		}
		
		private void detach_Wymienione_czescis(Wymienione_czesci entity)
		{
			this.SendPropertyChanging();
			entity.Rejestr_napraw = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wymienione_czesci")]
	public partial class Wymienione_czesci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_czesci;
		
		private int _nr_faktury;
		
		private EntityRef<Czesci> _Czesci;
		
		private EntityRef<Rejestr_napraw> _Rejestr_napraw;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_czesciChanging(int value);
    partial void Onid_czesciChanged();
    partial void Onnr_fakturyChanging(int value);
    partial void Onnr_fakturyChanged();
    #endregion
		
		public Wymienione_czesci()
		{
			this._Czesci = default(EntityRef<Czesci>);
			this._Rejestr_napraw = default(EntityRef<Rejestr_napraw>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czesci", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_czesci
		{
			get
			{
				return this._id_czesci;
			}
			set
			{
				if ((this._id_czesci != value))
				{
					if (this._Czesci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_czesciChanging(value);
					this.SendPropertyChanging();
					this._id_czesci = value;
					this.SendPropertyChanged("id_czesci");
					this.Onid_czesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_faktury", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nr_faktury
		{
			get
			{
				return this._nr_faktury;
			}
			set
			{
				if ((this._nr_faktury != value))
				{
					if (this._Rejestr_napraw.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnr_fakturyChanging(value);
					this.SendPropertyChanging();
					this._nr_faktury = value;
					this.SendPropertyChanged("nr_faktury");
					this.Onnr_fakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czesci_Wymienione_czesci", Storage="_Czesci", ThisKey="id_czesci", OtherKey="id_czesci", IsForeignKey=true)]
		public Czesci Czesci
		{
			get
			{
				return this._Czesci.Entity;
			}
			set
			{
				Czesci previousValue = this._Czesci.Entity;
				if (((previousValue != value) 
							|| (this._Czesci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Czesci.Entity = null;
						previousValue.Wymienione_czescis.Remove(this);
					}
					this._Czesci.Entity = value;
					if ((value != null))
					{
						value.Wymienione_czescis.Add(this);
						this._id_czesci = value.id_czesci;
					}
					else
					{
						this._id_czesci = default(int);
					}
					this.SendPropertyChanged("Czesci");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rejestr_napraw_Wymienione_czesci", Storage="_Rejestr_napraw", ThisKey="nr_faktury", OtherKey="nr_faktury", IsForeignKey=true)]
		public Rejestr_napraw Rejestr_napraw
		{
			get
			{
				return this._Rejestr_napraw.Entity;
			}
			set
			{
				Rejestr_napraw previousValue = this._Rejestr_napraw.Entity;
				if (((previousValue != value) 
							|| (this._Rejestr_napraw.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rejestr_napraw.Entity = null;
						previousValue.Wymienione_czescis.Remove(this);
					}
					this._Rejestr_napraw.Entity = value;
					if ((value != null))
					{
						value.Wymienione_czescis.Add(this);
						this._nr_faktury = value.nr_faktury;
					}
					else
					{
						this._nr_faktury = default(int);
					}
					this.SendPropertyChanged("Rejestr_napraw");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
